apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: api
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: evgeniymai/ita-api:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: ita-api
          env:
            - name: INTEVRIEW_INTUIT_TWITTER_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: intuit-twitter-config
                  key: INTEVRIEW_INTUIT_TWITTER_POSTGRES_PASSWORD
            - name: INTUIT_KEYWORD
              value: TurboTax
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: default
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: api
  type: LoadBalancer`