apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: sentiment-analyzer
  name: sentiment-analyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analyzer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sentiment-analyzer
    spec:
      containers:
        - image: evgeniymai/ita-sentiment-analyzer:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: ita-sentiment-analyzer
          env:
            - name: INTEVRIEW_INTUIT_TWITTER_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: intuit-twitter-config
                  key: INTEVRIEW_INTUIT_TWITTER_POSTGRES_PASSWORD
            - name: INTUIT_KEYWORD
              value: TurboTax
      restartPolicy: Always